CREATE DATABASE IF NOT EXISTS Coursework;
USE Coursework;

CREATE TABLE IF NOT EXISTS User (
UserID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(32) NOT NULL UNIQUE,
    Forename VARCHAR(64) NOT NULL,
    Surname VARCHAR(64) NOT NULL,
    Email VARCHAR(128) NOT NULL UNIQUE,
    Password VARCHAR(128) NOT NULL,
    Height INT,
    Weight INT
);

CREATE TABLE IF NOT EXISTS UserGroup (
GroupID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    GroupName VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS UserGroupMembership (
    GroupID INT NOT NULL,
    UserID INT NOT NULL,
    Role ENUM("Member", "Admin") DEFAULT ("Member"),
    PRIMARY KEY (GroupID, UserID),
    FOREIGN KEY (GroupID) REFERENCES UserGroup(GroupID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS Goal (
GoalID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Duration INT,
    Calories INT,
    Weight INT,
    Date date NOT NULL DEFAULT (CURDATE()),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Meal (
MealID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name varchar(32)
);

CREATE TABLE IF NOT EXISTS Food (
FoodID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(32) NOT NULL,
    Calories INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Drink (
DrinkID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(32) NOT NULL,
    Calories INT NOT NULL
);

CREATE TABLE IF NOT EXISTS MealFood (
    MealID INT NOT NULL,
    FoodID INT NOT NULL,
    Quantity INT DEFAULT 1,
    PRIMARY KEY (MealID, FoodID),
    FOREIGN KEY (MealID) REFERENCES Meal(MealID) ON DELETE CASCADE,
    FOREIGN KEY (FoodID) REFERENCES Food(FoodID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MealDrink (
    MealID INT NOT NULL,
    DrinkID INT NOT NULL,
    Quantity INT DEFAULT 1,
    PRIMARY KEY (MealID, DrinkID),
    FOREIGN KEY (MealID) REFERENCES Meal(MealID) ON DELETE CASCADE,
    FOREIGN KEY (DrinkID) REFERENCES Drink(DrinkID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DietEntry (
EntryID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    MealID INT NOT NULL,
    Date date NOT NULL DEFAULT (CURDATE()),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (MealID) REFERENCES Meal(MealID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ExerciseEntry (
EntryID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Activity ENUM("Running", "Walking", "Swimming", "Cycling", "Squats", "Pushups", "Situps"),
    UserID INT NOT NULL,
    Duration INT,
    Distance INT,
    Calories INT,
    Date date NOT NULL DEFAULT (CURDATE())
);